# Generated by Django 2.2.17 on 2021-01-13 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userProfile',
            new_name='userPost',
        ),
    ]
